### ISSUE TITLE
Upgrade of packages required

### ISSUE THREAD

**Issue by Derngineer** [joshbduncan/word-search-generator#61] opened 2024-01-22 04:51 UTC
typing extensions for this package are no longer compatible with most package requirements, had used it in my app but its not compatible with the rest of the apps cause of the old version. Noticed there 4.8 in the requirements. but why does installing default to 4.4

**Comment by Derngineer** [comment] 2024-01-22 04:55
Or the if possible the version could be made loose , cause version 4.4.0 of typing extensions doesnt work with other appss

**Comment by joshbduncan** [comment] 2024-01-22 18:24
I have never noticed this. It seems there is a metadata file that is generated when the package is built with the `build` module and that file still says `==4.4.0` even though the `pyproject.toml` file is specifies the latest version. Version 4.0.0 of this package is about to be released and it now has a minimum Python requirement of 3.10, so there will be no need for the `typing-extensions` package. I would just upgrade the version you have `pip install --upgrade typing_extensions` and all should work fine in the meantime. I will ensure that metadata file is correct on the next build and push. Thanks for the heads up!

**Comment by Dyson1664** [comment] 2024-04-30 10:51
I am having a similiar issue to @Derngineer 

I tried your suggestion and received this conflict

The conflict is caused by:
    The user requested typing_extensions==4.11.0
    openai 1.3.4 depends on typing-extensions<5 and >=4.5
    python-docx 1.1.0 depends on typing-extensions
    word-search-generator 3.5.0 depends on typing-extensions==4.4.0

**Comment by joshbduncan** [comment] 2024-05-07 11:05
@Dyson1664, it seems you are either trying to install `openai` and `python-docx` along with `word-search-generator`. Just install `word-search-generator` first, then `pip install --upgrade typing_extensions`, then pip install `openai` and `python-docx` and you should be good to go.

Fyi, this issue will be resolved in the next release word-search-generator.

Cheers!

**Comment by joshbduncan** [comment] 2024-05-15 16:14
Hotfixed with  #73.

**Closed** 2024-05-15 16:14 UTC
